apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rhdh-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: rhdh-sa
  namespace: rhdh-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rhdh-cluster-role