kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: openshift-gitops-server
  namespace: openshift-gitops
spec:
  host: openshift-gitops-server-openshift-gitops.apps-crc.testing
  to:
    kind: Service
    name: openshift-gitops-server
    weight: 100
  port:
    targetPort: http